name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # Checkout repo
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------
      # Python setup
      # ------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Airflow stable version

      # ------------------------
      # Install dependencies (Airflow + dbt)
      # ------------------------
      - name: Install Airflow and dbt
        run: |
          python -m pip install --upgrade pip
          pip install "apache-airflow==2.7.3" dbt-snowflake

      # ------------------------
      # Setup dbt profile
      # ------------------------
      - name: Setup dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          oilandgas_dbt:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ACCOUNTADMIN
                database: OILGAS_DB
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: raw
          EOL

      # ------------------------
      # Initialize Airflow DB
      # ------------------------
      - name: Initialize Airflow environment
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          mkdir -p $AIRFLOW_HOME/dags
          cp -r dags/* $AIRFLOW_HOME/dags/
          airflow db init
          airflow users create \
            --username admin \
            --firstname Air \
            --lastname Flow \
            --role Admin \
            --email admin@example.com \
            --password admin

      # ------------------------
      # Test ETL DAG
      # ------------------------
      - name: Run ETL DAG (ETL_pipeline)
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow dags test ETL_pipeline 2025-10-16

      # ------------------------
      # Test dbt DAG
      # ------------------------
      - name: Run dbt DAG (running_oilandgas_dbt)
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow dags test running_oilandgas_dbt 2025-10-16
